### ISSUE TITLE
Optimizar esquema de Features en DB

### ISSUE THREAD

**Issue by pgallardor** [alercebroker/alerce-scribe#51]
La idea es reducir la cantidad de operaciones en BD.
Se puede hacer replace en lugar de update.

Esquemas propuestos:
```python
object = {
  "features": {
    "ztf": {
       "g": [{"feat1": 10}, {"feat2": 20}],
       "r": [],
       "noband": [{"noband1: 5}]
    },
    "elasticc": {
       "g": [],
    }
  }
}

object = {
  "features": [
    {
      "feature_name": "feat1",
      "fid": "g",
      "version": "1.0",
      "value": 5,
      "group": "ztf"
    }
  ]
}
```

Criterio de aceptación
- Una operación por banda

**Comment by dirodriguezm** [comment]
Reopened to fix case for "bandless" features.

**Comment by dirodriguezm** [comment]
Cómo manejar las inconsistencias en detecciones para calcular las features ?

Si un cálculo de features para un objeto no incluye todas las detecciones, es terrible ?
Si ese cálculo se corrige con la siguiente alerta del mismo objeto estaría bien ?

**Comment by AlxEnashi** [comment]
EL esquema acordado es el siguiente:

```python
object = {
  "aid": "aid1",
  "tid": ztf,
  ...
  "features": {
    "ztf": {
          "version": "v1",
          "features": [
                {"name": "feature1", "band": "g", "value": 1234}
          ]
    }
  }
}

```

Con este esquema el comportamiento esperado es que cuando llegue un nuevo comando se cambie todo el contenido del diccionario del grupo correspondiente (ya sea ztf, lsst o atlas). En este ejemplo ztf.
No es relevante guardar los datros historicos de las features de versiones anteriores. [motivos: el mas importante es que serian features calculadas con menos puntos de la curva de luz asi que sus valores estan desactualizados]

**Comment by dirodriguezm** [comment]
Revisado ok
